# Site settings
title: "Equipment Rentals"
#baseurl: /RentTheme
baseurl: /

# Build settings
permalink: :title/
sass:
  sass_dir: css

plugins:
  - jekyll-seo-tag

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
