# Site settings
title: "Equipment Rentals"
email:
description:
url: /merudynamics.com
baseurl: /https://RentTheme

# Build settings
permalink: :title/
sass:
  sass_dir: css

plugins:
  - jekyll-seo-tag
